### ISSUE TITLE
make a release

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/kda#70] opened 2023-09-02 20:46 UTC
For the paper we should have
- [x] 0.1 release at minimum (EDIT: I mean an official release, not just a [0.1.0 pre release](https://github.com/Becksteinlab/kda/releases/tag/v0.1.0))
- [x] pypi package

**Comment by orbeckst** [comment] 2023-09-02 20:47
If you have any questions on how to do any of this, ask @ianmkenney , he has lots of experience!

**Comment by nawtrey** [comment] 2023-09-05 00:35
I made a new release, but I cannot update the binaries on PyPi as there is an issue with my account. It looks like that may take a week or more to resolve, but when I get access I can update PyPi.

**Comment by orbeckst** [comment] 2023-09-05 00:39
Ok... add me (=`Oliver.Beckstein` on pypi) as a co-maintainer next time so that at least one person has keys.

**Comment by nawtrey** [comment] 2024-03-08 05:18
Started working on this again, and I ran into an issue when running the tests locally. 

Here is the procedure I was following:

<details>
<summary>KDA PyPi Test/Upload Procedure</summary>

```
# Loosely follow GromacsWraper instructions
Link: https://github.com/Becksteinlab/GromacsWrapper/wiki/Preparing-a-release

# create a fresh conda env
conda create --name kda_fresh python=3.11
conda activate kda_fresh

# install pip, twine
python -m pip install -U pip twine

# clone the repo in a local directory
git clone git@github.com:Becksteinlab/kda.git

# install KDA and run the tests
cd kda
python setup.py install
python setup.py test
```

</details>

Here is the test output:

<details>
<summary>Test output</summary>

```
$ python setup.py test
C:\Users\nikol\Anaconda3\envs\kda_fresh\Lib\site-packages\setuptools\__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
C:\Users\nikol\Anaconda3\envs\kda_fresh\Lib\site-packages\setuptools\dist.py:314: InformationOnly: Normalizing 'v0.2.0+4.g533d243' to '0.2.0+4.g533d243'
  self.metadata.version = self._normalize_version(
running pytest
C:\Users\nikol\Anaconda3\envs\kda_fresh\Lib\site-packages\setuptools\command\test.py:193: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  ir_d = dist.fetch_build_eggs(dist.install_requires)
C:\Users\nikol\Anaconda3\envs\kda_fresh\Lib\site-packages\setuptools\command\test.py:194: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  tr_d = dist.fetch_build_eggs(dist.tests_require or [])
C:\Users\nikol\Anaconda3\envs\kda_fresh\Lib\site-packages\setuptools\command\test.py:195: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  er_d = dist.fetch_build_eggs(
running egg_info
writing kda.egg-info\PKG-INFO
writing dependency_links to kda.egg-info\dependency_links.txt
writing requirements to kda.egg-info\requires.txt
writing top-level names to kda.egg-info\top_level.txt
reading manifest file 'kda.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
adding license file 'LICENSE'
writing manifest file 'kda.egg-info\SOURCES.txt'
running build_ext
============================= test session starts =============================
platform win32 -- Python 3.11.8, pytest-8.0.2, pluggy-1.4.0
rootdir: C:\Users\nikol\OneDrive\projects\kinetic_diagram_analysis\packages\kda
plugins: cov-4.1.0, xdist-3.5.0, hypothesis-6.98.17
collected 21 items / 1 error

=================================== ERRORS ====================================
___________________ ERROR collecting kda/tests/test_kda.py ____________________
kda\tests\test_kda.py:13: in <module>
    from kda import calculations, diagrams, graph_utils, expressions, ode, svd
kda\calculations.py:25: in <module>
    from sympy import logcombine
c:\users\nikol\anaconda3\envs\kda_fresh\lib\site-packages\sympy-1.12-py3.11.egg\sympy\__init__.py:30: in <module>
    from sympy.core.cache import lazy_function
c:\users\nikol\anaconda3\envs\kda_fresh\lib\site-packages\sympy-1.12-py3.11.egg\sympy\core\__init__.py:9: in <module>
    from .expr import Expr, AtomicExpr, UnevaluatedExpr
c:\users\nikol\anaconda3\envs\kda_fresh\lib\site-packages\sympy-1.12-py3.11.egg\sympy\core\expr.py:4159: in <module>
    from .mul import Mul
c:\users\nikol\anaconda3\envs\kda_fresh\lib\site-packages\sympy-1.12-py3.11.egg\sympy\core\mul.py:2193: in <module>
    from .numbers import Rational
c:\users\nikol\anaconda3\envs\kda_fresh\lib\site-packages\sympy-1.12-py3.11.egg\sympy\core\numbers.py:4567: in <module>
    _sympy_converter[type(mpmath.rational.mpq(1, 2))] = sympify_mpmath_mpq
E   AttributeError: module 'mpmath' has no attribute 'rational'
============================== warnings summary ===============================
..\..\..\..\..\anaconda3\envs\kda_fresh\lib\site-packages\mpmath-1.4.0a0-py3.11.egg\mpmath\ctx_mp.py:28
  c:\users\nikol\anaconda3\envs\kda_fresh\lib\site-packages\mpmath-1.4.0a0-py3.11.egg\mpmath\ctx_mp.py:28: DeprecationWarning: mpnumeric is deprecated
    warnings.warn(f"{name} is deprecated", DeprecationWarning)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ===========================
ERROR kda/tests/test_kda.py - AttributeError: module 'mpmath' has no attribut...
!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 1 error in 4.29s =========================
```

</details>

It appears the tests fail due to an issue with one of `SymPy`'s dependencies (i.e. `mpmath`) where it is installing a pre-release that is broken (see [this issue](https://github.com/sympy/sympy/issues/26273)). From the comments it looks like I could try to downgrade `mpmath` and re-run the tests, but I think that's bad practice. 

There is also the issue regarding `194: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.`/`PEP 517`, I'll have to look into that separately.

Any advice on how to proceed?

**Comment by orbeckst** [comment] 2024-03-08 15:39
You can exclude certain versions in your dependencies or just state compatibility with <= known good version. That’s much better than breaking and safer because at least you know it works. Am 3/7/24 um 22:18 schrieb Nik Awtrey ***@***.***>:﻿
Started working on this again, and I ran into an issue when running the tests locally.
Here is the procedure I was following:

KDA PyPi Test/Upload Procedure
# Loosely follow GromacsWraper instructions
Link: https://github.com/Becksteinlab/GromacsWrapper/wiki/Preparing-a-release

# create a fresh conda env
conda create --name kda_fresh python=3.11
conda activate kda_fresh

# install pip, twine
python -m pip install -U pip twine

# clone the repo in a local directory
git clone ***@***.***:Becksteinlab/kda.git

# install KDA and run the tests
cd kda
python setup.py install
python setup.py test


Here is the test output:

Test output
$ python setup.py test
C:\Users\nikol\Anaconda3\envs\kda_fresh\Lib\site-packages\setuptools\__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
C:\Users\nikol\Anaconda3\envs\kda_fresh\Lib\site-packages\setuptools\dist.py:314: InformationOnly: Normalizing 'v0.2.0+4.g533d243' to '0.2.0+4.g533d243'
  self.metadata.version = self._normalize_version(
running pytest
C:\Users\nikol\Anaconda3\envs\kda_fresh\Lib\site-packages\setuptools\command\test.py:193: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  ir_d = dist.fetch_build_eggs(dist.install_requires)
C:\Users\nikol\Anaconda3\envs\kda_fresh\Lib\site-packages\setuptools\command\test.py:194: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  tr_d = dist.fetch_build_eggs(dist.tests_require or [])
C:\Users\nikol\Anaconda3\envs\kda_fresh\Lib\site-packages\setuptools\command\test.py:195: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  er_d = dist.fetch_build_eggs(
running egg_info
writing kda.egg-info\PKG-INFO
writing dependency_links to kda.egg-info\dependency_links.txt
writing requirements to kda.egg-info\requires.txt
writing top-level names to kda.egg-info\top_level.txt
reading manifest file 'kda.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
adding license file 'LICENSE'
writing manifest file 'kda.egg-info\SOURCES.txt'
running build_ext
============================= test session starts =============================
platform win32 -- Python 3.11.8, pytest-8.0.2, pluggy-1.4.0
rootdir: C:\Users\nikol\OneDrive\projects\kinetic_diagram_analysis\packages\kda
plugins: cov-4.1.0, xdist-3.5.0, hypothesis-6.98.17
collected 21 items / 1 error

=================================== ERRORS ====================================
___________________ ERROR collecting kda/tests/test_kda.py ____________________
kda\tests\test_kda.py:13: in <module>
    from kda import calculations, diagrams, graph_utils, expressions, ode, svd
kda\calculations.py:25: in <module>
    from sympy import logcombine
c:\users\nikol\anaconda3\envs\kda_fresh\lib\site-packages\sympy-1.12-py3.11.egg\sympy\__init__.py:30: in <module>
    from sympy.core.cache import lazy_function
c:\users\nikol\anaconda3\envs\kda_fresh\lib\site-packages\sympy-1.12-py3.11.egg\sympy\core\__init__.py:9: in <module>
    from .expr import Expr, AtomicExpr, UnevaluatedExpr
c:\users\nikol\anaconda3\envs\kda_fresh\lib\site-packages\sympy-1.12-py3.11.egg\sympy\core\expr.py:4159: in <module>
    from .mul import Mul
c:\users\nikol\anaconda3\envs\kda_fresh\lib\site-packages\sympy-1.12-py3.11.egg\sympy\core\mul.py:2193: in <module>
    from .numbers import Rational
c:\users\nikol\anaconda3\envs\kda_fresh\lib\site-packages\sympy-1.12-py3.11.egg\sympy\core\numbers.py:4567: in <module>
    _sympy_converter[type(mpmath.rational.mpq(1, 2))] = sympify_mpmath_mpq
E   AttributeError: module 'mpmath' has no attribute 'rational'
============================== warnings summary ===============================
..\..\..\..\..\anaconda3\envs\kda_fresh\lib\site-packages\mpmath-1.4.0a0-py3.11.egg\mpmath\ctx_mp.py:28
  c:\users\nikol\anaconda3\envs\kda_fresh\lib\site-packages\mpmath-1.4.0a0-py3.11.egg\mpmath\ctx_mp.py:28: DeprecationWarning: mpnumeric is deprecated
    warnings.warn(f"{name} is deprecated", DeprecationWarning)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ===========================
ERROR kda/tests/test_kda.py - AttributeError: module 'mpmath' has no attribut...
!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 1 error in 4.29s =========================


It appears the tests fail due to an issue with one of SymPy's dependencies (i.e. mpmath) where it is installing a pre-release that is broken (see this issue). From the comments it looks like I could try to downgrade mpmath and re-run the tests, but I think that's bad practice.
There is also the issue regarding 194: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated./PEP 517, I'll have to look into that separately.
Any advice on how to proceed?

**Comment by nawtrey** [comment] 2024-03-09 01:12
Uninstalling `sympy` and `mpmath` and reinstalling with `pip install -U sympy mpmath==1.3` ([latest non-pre-release version](https://pypi.org/project/mpmath/#history))  allowed the tests to run to completion:

```
============================= test session starts =============================
platform win32 -- Python 3.11.8, pytest-8.0.2, pluggy-1.4.0
rootdir: C:\Users\nikol\OneDrive\projects\kinetic_diagram_analysis\packages\kda
plugins: cov-4.1.0, xdist-3.5.0, hypothesis-6.98.17
collected 64 items

kda\tests\test_kda.py ...........................................        [ 67%]
kda\tests\test_plotting.py .....................                         [100%]

======================== 64 passed in 79.35s (0:01:19) ========================
```

I can pin `mpmath` to `v1.3.0` as a temporary solution until the pre-release/`sympy` issue is sorted out. It looks like the `sympy` folks are doing the same thing upstream (see [issue](https://github.com/pytorch/botorch/pull/2222)). 

I'll open an issue regarding the pinning of `mpmath`, and another for unpinning when `sympy` `v1.13` is released. While I'm at it, I'll open another issue regarding the `PEP 517` issue.

**Comment by nawtrey** [comment] 2024-03-10 02:00
Small update -- using `python setup.py install` seems to be causing most of these issues. If I use the recommended commands via `pip` (see [link](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/)) I don't run into any issues with `mpmath`, and the tests run just fine using `pytest`:
```
$ python -m pytest
============================= test session starts =============================
platform win32 -- Python 3.11.8, pytest-8.1.1, pluggy-1.4.0
rootdir: C:\Users\nikol\OneDrive\projects\kinetic_diagram_analysis\packages\kda
plugins: hypothesis-6.99.0
collected 64 items

kda\tests\test_kda.py ...........................................        [ 67%]
kda\tests\test_plotting.py .....................                         [100%]

======================= 64 passed in 104.10s (0:01:44) ========================
```

<details>
<summary> updated procedure </summary>

```
# create a fresh conda env
conda create -n kda_fresh python=3.11
conda activate kda_fresh

# install pip, twine, build, pytest
python -m pip install -U pip twine build pytest

# clone the repo in a local directory
git clone git@github.com:Becksteinlab/kda.git
cd kda

# install KDA and run the tests
# NOTE: these commands are deprecated
# See: https://packaging.python.org/en/latest/discussions/setup-py-deprecated/
<!-- python setup.py install -->
<!-- python setup.py test -->

# it looks like we should do the following instead
# NOTE: tests may not run if `hypothesis` is not installed
python -m pip install .
python -m pip install -U hypothesis
pytest
```

</details>

I believe this was also the cause of the `PEP 517` complaints I was getting. I think as long as the modern commands are working I can just ignore the `mpmath` issue and move forward with `PyPi` things.

**Comment by orbeckst** [comment] 2024-03-10 02:21
Yes, setup.py install is deprecated anyway. You might be able to just have a pyproject.toml file.Am 3/9/24 um 19:00 schrieb Nik Awtrey ***@***.***>:﻿
Small update -- using python setup.py install seems to be causing most of these issues. If I use the recommended commands via pip (see link) I don't run into any issues with mpmath, and the tests run just fine using pytest:
$ python -m pytest
============================= test session starts =============================
platform win32 -- Python 3.11.8, pytest-8.1.1, pluggy-1.4.0
rootdir: C:\Users\nikol\OneDrive\projects\kinetic_diagram_analysis\packages\kda
plugins: hypothesis-6.99.0
collected 64 items

kda\tests\test_kda.py ...........................................        [ 67%]
kda\tests\test_plotting.py .....................                         [100%]

======================= 64 passed in 104.10s (0:01:44) ========================


 updated procedure 
# create a fresh conda env
conda create -n kda_fresh python=3.11
conda activate kda_fresh

# install pip, twine, build, pytest
python -m pip install -U pip twine build pytest

# clone the repo in a local directory
git clone ***@***.***:Becksteinlab/kda.git
cd kda

# install KDA and run the tests
# NOTE: these commands are deprecated
# See: https://packaging.python.org/en/latest/discussions/setup-py-deprecated/



# it looks like we should do the following instead
# NOTE: tests may not run if `hypothesis` is not installed
python -m pip install .
python -m pip install -U hypothesis
pytest


I believe this was also the cause of the PEP 517 complaints I was getting. I think as long as the modern commands are working I can just ignore the mpmath issue and move forward with PyPi things.

**Comment by nawtrey** [comment] 2024-03-19 02:31
The current version of KDA (`v0.3.0`) is now available on PyPi [here](https://pypi.org/project/kda/0.3.0/#history). Closing this issue.

**Closed by nawtrey** 2024-03-19 02:31 UTC

**Comment by orbeckst** [comment] 2024-03-19 04:57
Hooray 🍾 !
